pipeline {
    agent any
    stages {
        stage("Checkout"){
            steps {
                checkout scm
            }
        }
        stage("Setup") {
            steps {
                sh './gradlew setup'
            }
        }
        stage("Build") {
            steps {
                sh './gradlew :modules:lambda-service:build -Pbuild_number=$BUILD_NUMBER'
            }
        }
    }

}